/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Method Not Allowed */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserPatchDto"];
                    "text/json": components["schemas"]["UserPatchDto"];
                    "application/*+json": components["schemas"]["UserPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Method Not Allowed */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/active-team-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": number;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/emergency-alert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserEmergencyAlertDto"];
                    "text/json": components["schemas"]["CreateUserEmergencyAlertDto"];
                    "application/*+json": components["schemas"]["CreateUserEmergencyAlertDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserEmergencyAlertDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/active-emergency-alert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MyUserEmergencyAlertDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/emergency-alert/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteUserEmergencyAlertDto"];
                    "text/json": components["schemas"]["CompleteUserEmergencyAlertDto"];
                    "application/*+json": components["schemas"]["CompleteUserEmergencyAlertDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserEmergencyAlertDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/location-privacy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserLocationPrivacyDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserLocationPrivacyPatchDto"];
                    "text/json": components["schemas"]["UserLocationPrivacyPatchDto"];
                    "application/*+json": components["schemas"]["UserLocationPrivacyPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserLocationPrivacyDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/users/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    clientApplicationId?: number;
                    clientDevicePlatformId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSettingsDto"][];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserSettingsPutDto"];
                    "text/json": components["schemas"]["UserSettingsPutDto"];
                    "application/*+json": components["schemas"]["UserSettingsPutDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserSettingsDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LanguageDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LanguageDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateLanguageDto"];
                    "text/json": components["schemas"]["CreateLanguageDto"];
                    "application/*+json": components["schemas"]["CreateLanguageDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LanguageDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/{lang}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    lang: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TranslationTokenAdminDto"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/{lang}/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    lang: string;
                    tokenId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTranslationDto"];
                    "text/json": components["schemas"]["UpdateTranslationDto"];
                    "application/*+json": components["schemas"]["UpdateTranslationDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TranslationEntryDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/translations/{lang}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    since?: number;
                };
                header?: never;
                path: {
                    lang: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TranslationTableDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/translations/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReportUnknownTranslationsDto"];
                    "text/json": components["schemas"]["ReportUnknownTranslationsDto"];
                    "application/*+json": components["schemas"]["ReportUnknownTranslationsDto"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team/{teamId}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    teamId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamContextDelta"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Gone */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team/{teamId}/context/delta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    latestUpdateDate?: number;
                    notActiveTeamUserIds?: number[];
                };
                header?: never;
                path: {
                    teamId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamContextDelta"];
                    };
                };
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Gone */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTeamDto"];
                    "text/json": components["schemas"]["CreateTeamDto"];
                    "application/*+json": components["schemas"]["CreateTeamDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team/{teamId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    teamId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    teamId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeamPatchDto"];
                    "text/json": components["schemas"]["TeamPatchDto"];
                    "application/*+json": components["schemas"]["TeamPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/team/{teamId}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    teamId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    teamId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeamPatchDto"];
                    "text/json": components["schemas"]["TeamPatchDto"];
                    "application/*+json": components["schemas"]["TeamPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/media/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        File?: components["schemas"]["IFormFile"];
                        OriginalFileName?: string;
                        /** Format: uint8 */
                        MediaType?: number;
                        Guid?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadedMediaDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mobile-gps/location-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JsonArray"];
                    "text/json": components["schemas"]["JsonArray"];
                    "application/*+json": components["schemas"]["JsonArray"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client-log-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        UserDescription?: string;
                        IssueContext?: string;
                        ClientSideInfo?: string;
                        ClientSideDate?: string;
                        File?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginData"];
                    "text/json": components["schemas"]["LoginData"];
                    "application/*+json": components["schemas"]["LoginData"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientSideInfo"];
                    "text/json": components["schemas"]["ClientSideInfo"];
                    "application/*+json": components["schemas"]["ClientSideInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/check-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientSideInfo"];
                    "text/json": components["schemas"]["ClientSideInfo"];
                    "application/*+json": components["schemas"]["ClientSideInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth_auto/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientSideInfo"];
                    "text/json": components["schemas"]["ClientSideInfo"];
                    "application/*+json": components["schemas"]["ClientSideInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth_auto/check-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientSideInfo"];
                    "text/json": components["schemas"]["ClientSideInfo"];
                    "application/*+json": components["schemas"]["ClientSideInfo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authtest/tokentest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActiveUserEmergencyAlertDto: {
            /** Format: int32 */
            UserId?: number;
            /** Format: int32 */
            MobileGpsDeviceId?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            CreatedDate?: number;
            /** Format: double */
            Latitude?: number;
            /** Format: double */
            Longitude?: number;
        };
        ClientSideInfo: {
            AppUID?: string;
            AppVersion?: string;
            DeviceUID?: string;
            CodeVersion?: string;
            PlatformName?: string;
            /** Format: int16 */
            PlatformId?: number;
            FCM_FID?: string;
        };
        CompleteUserEmergencyAlertDto: {
            /** Format: double */
            CompleteLatitude?: number;
            /** Format: double */
            CompleteLongitude?: number;
        };
        CreateLanguageDto: {
            Code?: string;
            EnglishName?: string;
            NativeName?: string;
            IsEnabled?: boolean;
        };
        CreateTeamDto: {
            TeamName?: string;
            /** Format: int16 */
            StatusId?: number;
            JoinKey?: string;
        };
        CreateUserEmergencyAlertDto: {
            /** Format: double */
            Latitude?: number;
            /** Format: double */
            Longitude?: number;
        };
        /** Format: binary */
        IFormFile: string;
        InboundUploadedMediaDto: {
            Url?: string;
            Guid?: string;
            /** Format: int16 */
            GroupKey?: number;
            /** Format: uint8 */
            MediaType?: number;
        };
        JsonArray: unknown[];
        LanguageDto: {
            Code?: string;
            EnglishName?: string;
            NativeName?: string;
            IsEnabled?: boolean;
        };
        LoginData: {
            UserName: string;
            Password: string;
            RememberMe?: boolean;
        };
        MobileGpsDeviceDto: {
            /** Format: int32 */
            Id?: number;
            /** Format: int32 */
            UserId?: number;
            Name?: string;
        };
        MobileGpsDeviceMapStateDto: {
            /** Format: int32 */
            MobileGpsDeviceId?: number;
            /** Format: int32 */
            UserId?: number;
            /** Format: double */
            Latitude?: number;
            /** Format: double */
            Longitude?: number;
            /** Format: int16 */
            MotionActivity?: number;
            /** Format: float */
            Speed?: number;
            /** Format: int16 */
            Dir?: number;
            /** Format: float */
            BatteryLevel?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            LatestOnMapUpdate?: number;
        };
        MyUserEmergencyAlertDto: {
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            CreatedDate?: number;
            /** Format: int32 */
            MobileGpsDeviceId?: number;
            /** Format: double */
            Latitude?: number;
            /** Format: double */
            Longitude?: number;
        };
        ProblemDetails: {
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            instance?: string;
        };
        ReportUnknownTranslationsDto: {
            Texts?: string[];
        };
        TeamActivityDto: {
            /** Format: int32 */
            Id?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            Date?: number;
            /** Format: int32 */
            UserId?: number;
            /** Format: int16 */
            ActivityTypeId?: number;
            /** Format: double */
            Latitude?: number;
            /** Format: double */
            Longitude?: number;
            Message?: string;
            /** Format: int16 */
            UserReadStatusId?: number;
        };
        TeamContextDelta: {
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            LastUpdate?: number;
            TeamHeader?: null | components["schemas"]["TeamHeaderDto"];
            TeamDetails?: null | components["schemas"]["TeamDetailsDto"];
            TeamUploadedMedias?: components["schemas"]["UploadedMediaDto"][];
            RemoveTeamMediaIds?: number[];
            Members?: components["schemas"]["TeamMemberUserDto"][];
            RemoveMemberUserIds?: number[];
            TeamPrimaryTargetUser?: null | components["schemas"]["TeamPrimaryTargetUserDto"];
            DoRemoveTeamPrimaryTargetUser?: boolean;
            Users?: components["schemas"]["UserDto"][];
            RemoveUserIds?: number[];
            MobileGpsDevices?: components["schemas"]["MobileGpsDeviceDto"][];
            RemoveMobileGpsDeviceIds?: number[];
            UserAlerts?: components["schemas"]["ActiveUserEmergencyAlertDto"][];
            RemoveUserAlertIds?: number[];
            UserMessages?: components["schemas"]["UserMessageDto"][];
            RemoveUserMessageIds?: number[];
            TeamActivities?: components["schemas"]["TeamActivityDto"][];
            GpsDeviceMapStates?: components["schemas"]["MobileGpsDeviceMapStateDto"][];
        };
        TeamDetailsDto: {
            Notes?: string;
        };
        TeamDto: {
            Notes?: string;
            /** Format: int32 */
            Id?: number;
            /** Format: int32 */
            CreatorUserId?: number;
            TeamName?: string;
            /** Format: int16 */
            StatusId?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            CreatedDate?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            ClosedDate?: number;
            JoinKey?: string;
            JoinQrCode?: string;
        };
        TeamHeaderDto: {
            /** Format: int32 */
            Id?: number;
            /** Format: int32 */
            CreatorUserId?: number;
            TeamName?: string;
            /** Format: int16 */
            StatusId?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            CreatedDate?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            ClosedDate?: number;
            JoinKey?: string;
            JoinQrCode?: string;
        };
        TeamMemberUserDto: {
            /** Format: int32 */
            UserId?: number;
            /** Format: int16 */
            RoleId?: number;
            /** Format: int16 */
            IconKey?: number;
        };
        TeamPatchDto: {
            TeamName?: string;
            /** Format: int16 */
            StatusId?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            ClosedDate?: null | number;
            JoinKey?: null | string;
        };
        TeamPrimaryTargetUserDto: {
            /** Format: int32 */
            TargetUserId?: number;
            /** Format: int32 */
            UpdatedByUserId?: number;
            /** Format: int16 */
            StatusId?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            LatestUpdate?: number;
        };
        TranslationEntryDto: {
            Text?: string;
            Translation?: string;
        };
        TranslationTableDto: {
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            AsOf?: number;
            Tokens?: components["schemas"]["TranslationEntryDto"][];
        };
        TranslationTokenAdminDto: {
            /** Format: int32 */
            TokenId?: number;
            Text?: string;
            Context?: string;
            Translation?: string;
            /** Format: int32 */
            ReportCount?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            LastSeenAt?: number;
        };
        UpdateTranslationDto: {
            TranslatedText?: null | string;
        };
        UploadedMediaDto: {
            /** Format: int32 */
            Id?: number;
            Url?: string;
            /** Format: int16 */
            GroupKey?: number;
            PreviewUrl?: string;
            /** Format: uint8 */
            MediaType?: number;
        };
        UserDto: {
            /** Format: int32 */
            Id?: number;
            DisplayName?: string;
            UserName?: string;
            FullName?: string;
            Phone?: string;
            Email?: string;
            AvatarImage?: null | components["schemas"]["UploadedMediaDto"];
            GovIDImage?: null | components["schemas"]["UploadedMediaDto"];
        };
        UserEmergencyAlertDto: {
            /** Format: int32 */
            Id?: number;
            /** Format: int32 */
            UserId?: number;
            /** Format: int32 */
            MobileGpsDeviceId?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            CreatedDate?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            CompletedDate?: number;
            /** Format: double */
            Latitude?: number;
            /** Format: double */
            Longitude?: number;
            /** Format: double */
            CompleteLatitude?: number;
            /** Format: double */
            CompleteLongitude?: number;
            /** Format: int16 */
            StatusId?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            LatestUpdate?: number;
        };
        UserLocationPrivacyDto: {
            /** Format: int16 */
            PrivacyMode?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            LatestUpdate?: number;
        };
        UserLocationPrivacyPatchDto: {
            /** Format: int16 */
            PrivacyMode?: number;
        };
        UserMessageDto: {
            /** Format: int32 */
            Id?: number;
            /** Format: int32 */
            UserId?: number;
            /**
             * Format: int64
             * @description Unix timestamp (seconds since epoch, UTC)
             */
            Date?: number;
            /** Format: int32 */
            ToUserId?: number;
            Message?: string;
            /** Format: int16 */
            UserReadStatusId?: number;
        };
        UserPatchDto: {
            DisplayName?: string;
            FullName?: null | string;
            Phone?: null | string;
            Email?: null | string;
            InsertMedias?: components["schemas"]["InboundUploadedMediaDto"][];
            RemoveMediaIds?: number[];
        };
        UserSettingsDto: {
            Name?: string;
            Value?: string;
        };
        UserSettingsPutDto: {
            Name?: string;
            Value?: null | string;
            /** Format: int16 */
            ClientApplicationId?: null | number;
            /** Format: int16 */
            ClientDevicePlatformId?: null | number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
